version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      
  test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: Run tests
          command: |
            gotestsum --junitfile /tmp/artifacts/unit-tests.xml ./...
      - store_test_results:
          path: /tmp/artifacts/test-reports
      - store_artifacts:
         path: /tmp/artifacts/test-reports
  

workflows:
  build_and_test:
    jobs:
      - build
      - test