# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.1
    steps:
      - checkout
      - run:
          name: Install Go 1.19
          command: |
              sudo rm -rf /usr/local/go
              wget -O go.tgz https://dl.google.com/go/go1.19.linux-amd64.tar.gz
              sudo tar -C /usr/local -xzf go.tgz
              which go
              go version
      - run:
          name: Run vet
          command: |
              go vet ./...
      - run:
          name: Run staticheck
          command: |
            wget -O staticcheck.tgz https://github.com/dominikh/go-tools/releases/download/v0.3.3/staticcheck_linux_amd64.tar.gz
            sudo tar -xzf staticcheck.tgz
              ./staticcheck/staticcheck --version
              ./staticcheck/staticcheck -checks=all ./...
      - run:
          name: Download the DB image
          command: |
              docker pull postgres:15-alpine
      - run:
          name: Run tests
          command: |
              go test ./...
              